window.SITE_CONFIG = {
  site: {
    title: "АкваБлеск",
    phoneDisplay: "+7 (914) 582-63-17",
    phoneHref: "tel:+79145826317",
    city: "Хабаровск",
    hours: "Ежедневно 09:00–22:00",
    address: "Хабаровск, центр города",
  },
  messenger: {
    name: "MAX",
    url: "https://max.ru/",
    heroLabel: "Написать в MAX",
    contactsLabel: "Перейти в MAX",
    ariaLabel: "Перейти в MAX",
    openInNewTab: true,
  },
  formService: {
    endpoint: "/api/leads",
    method: "POST",
    accept: "application/json",
    provider: "aquablesk-backend",
    redirectHash: "#thank-you",
    successMessage: "Ваша заявка принята, ожидайте звонка, мы скоро с вами свяжемся.",
    loadingMessage: "Отправляем заявку...",
    errorMessage: "Не удалось отправить заявку. Попробуйте ещё раз позже или свяжитесь с нами по телефону.",
    missingEndpointMessage: "Форма ещё не подключена к сервису заявок.",
  },
  contactMap: {
    title: "АкваБлеск в Хабаровске",
    note: "Откройте карту, посмотрите точку и постройте маршрут.",
    address: "Хабаровск, центр города",
    lat: 48.480223,
    lng: 135.071917,
    zoom: 15,
    routeUrl: "https://www.google.com/maps/dir/?api=1&destination=48.480223,135.071917",
  },
  reviewCards: {
    gis: {
      title: "Отзыв в 2ГИС",
      text: "Помогите другим выбрать нас — оставьте честный отзыв о качестве уборки",
      buttonLabel: "Подробнее",
      buttonUrl: "https://2gis.ru/",
      reviewUrl: "https://2gis.ru/",
      qrUrl: "https://2gis.ru/",
      qrImage: "assets/qr-2gis.svg",
      qrAlt: "QR-код для перехода к отзыву в 2ГИС",
      openInNewTab: true,
    },
    yandex: {
      title: "Оставить отзыв в Яндекс",
      text: "Поделитесь впечатлением об уборке — это помогает нам расти и повышать качество сервиса",
      buttonLabel: "Перейти",
      buttonUrl: "https://yandex.ru/maps/",
      reviewUrl: "https://yandex.ru/maps/",
      qrUrl: "https://yandex.ru/maps/",
      qrImage: "assets/qr-yandex.svg",
      qrAlt: "QR-код для перехода к отзыву в Яндекс",
      openInNewTab: true,
    },
  },
  reviewsIntegration: {
    provider: "yandex-widget",
    yandexWidgetUrl: "",
    yandexBusinessUrl: "https://yandex.ru/maps/",
    gisBusinessUrl: "https://2gis.ru/",
    note: "Для автоматического показа отзывов используется официальный виджет Яндекс Карт или серверная синхронизация.",
  },
};
